### PR TITLE
Simplified Chinese Support

### PR DESCRIPTION
**Pull request by hiki8man**
Add Simplified Chinese language file

### CODE REVIEW

**Comment by R3alCl0ud** [comment]
Hi, can you update the translation to include the new fields I just added?

**Comment by R3alCl0ud** [comment]
Also, how should simplified Chinese be written in the UI?

**Comment by hiki8man** [comment]
i update translation file now
i don't understand what is Scale use for so i didn't translation it
in UI simplified Chinese should be write 简体中文

**Comment by R3alCl0ud** [comment]
Scale is how big everything should be displayed.

**Comment by hiki8man** [comment]
i'm add Scale translation and everything should be fine now

**Pull request merged**
